In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("cardio_train.csv",sep=";")

In [3]:
data

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [4]:
data.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [6]:
data.tail(5)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [7]:
#avarage age in this data set

data['age'].mean()

19468.865814285713

In [8]:
#here age in days so convert into years

data['age_in_year'] = (data['age']/365).astype('int64')

In [9]:
data['age_in_year'].mean()

52.840671428571426

In [10]:
data['ap_hi'].mean()

128.8172857142857

In [11]:
data['ap_hi'].median()

120.0

In [12]:
data['ap_lo'].mean()

96.63041428571428

In [13]:
data['ap_lo'].median()

80.0

In [14]:
 # Women with heart disease

women_with_cardio = data[(data['gender'] == 1) & (data['cardio'] == 1)].shape[0]
women_with_cardio

22616

In [15]:
#men_with_heart disease
men_with_cardio = data[(data['gender'] == 2) & (data['cardio'] == 1)].shape[0]
men_with_cardio

12363

In [16]:
# What percentage of people have cholesterol = 3 (well above normal)?
(data[data['cholesterol']==3].shape[0]/data.shape[0])*100

11.522857142857143

In [17]:
#how many people are smokers
data[data['smoke']==1].shape[0]

6169

In [18]:
#how many people are non-smokers
data[data['smoke']==0].shape[0]

63831

In [19]:
#how many patient with high glucose,high cholesterol and cardio = 1

subset = data[(data['cholesterol'] == 3)&(data['gluc'] == 3)&(data['cardio'] == 1)]

count = subset.shape[0]

(count/data.shape[0])*100

3.4357142857142855

In [20]:
#Does physical activity (active) reduce the chance of having cardio = 1?

acti = data.groupby('active')['cardio'].mean()
acti

active
0    0.535774
1    0.490891
Name: cardio, dtype: float64

In [30]:
data[data['height']>=250]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_in_year
6486,9223,21220,1,250,86.0,140,100,3,1,0,0,1,1,58

In [40]:
data[(data['weight']>=200)|(data['weight']<=30)]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_in_year
435,618,16765,1,186,200.0,130,70,1,1,0,0,0,0,45
3752,5306,15400,1,120,30.0,110,70,1,1,0,0,1,0,42
18559,26503,18140,1,160,30.0,120,80,1,1,0,0,1,1,49
26806,38312,23284,1,157,23.0,110,80,1,1,0,0,1,0,63
29488,42156,20408,2,177,22.0,120,80,1,1,1,1,1,0,55
33817,48318,21582,2,178,11.0,130,90,1,1,0,0,1,1,59
34276,48976,14664,2,128,28.0,120,80,1,1,0,0,1,0,40
41905,59853,21334,1,143,30.0,103,61,2,1,0,0,1,0,58
50413,71945,15117,2,180,200.0,150,90,1,1,0,0,1,1,41
57858,82567,18804,2,165,10.0,180,1100,2,2,0,0,1,1,51
60188,85931,21855,1,162,21.0,120,80,2,1,0,0,1,1,59
60699,86650,18875,1,171,29.0,110,70,2,1,0,0,1,1,51

In [42]:
data['ap_hi'].value_counts()

ap_hi
 120     27699
 140      9506
 130      8961
 110      8644
 150      4450
         ...
 1620        1
 199         1
-150         1
-115         1
 2000        1
Name: count, Length: 153, dtype: int64

In [44]:
data[(data['ap_hi'] <= 70) | (data['ap_hi'] >= 250)]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_in_year
567,815,21281,1,168,78.0,14,90,2,1,0,0,1,1,58
636,913,20457,2,169,68.0,70,110,1,1,0,0,1,0,56
927,1294,21867,2,175,70.0,14,90,3,1,0,0,1,1,59
979,1360,18225,1,172,65.0,11,80,1,3,0,0,1,0,49
1600,2260,19201,1,165,66.0,12,80,1,1,0,0,1,0,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68742,98213,18755,1,158,74.0,14,90,1,1,0,0,1,1,51
68998,98568,19107,1,154,77.0,14,90,1,1,0,0,1,0,52
69137,98743,15442,2,176,65.0,12,80,1,1,0,0,1,0,42
69370,99089,14696,1,170,74.0,2000,100,2,1,0,0,1,1,40
69549,99328,21243,1,155,69.0,13,90,1,3,0,0,1,1,58